catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.1
  vite-plus: 1.0.0-rc.1
  '@types/node': ^26.6.3
  '@typescript/native-preview': 7.0.0-dev.20260707.2
  bumpp: ^12.3.0
  typescript: ^7.0.2
minimumReleaseAgeExclude:
  - '@voidzero-dev/vite-plus-core@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-arm64@0.2.9'
  - '@voidzero-dev/vite-plus-darwin-x64@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@0.2.9'
  - '@voidzero-dev/vite-plus-linux-x64-musl@0.2.9'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.9'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@0.2.9'
  - vite-plus@0.2.9
  - '@voidzero-dev/vite-plus-core@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-darwin-arm64@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-darwin-x64@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-linux-arm64-gnu@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-linux-arm64-musl@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-linux-x64-gnu@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-linux-x64-musl@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-win32-arm64-msvc@1.0.0-rc.1'
  - '@voidzero-dev/vite-plus-win32-x64-msvc@1.0.0-rc.1'
  - vite-plus@1.0.0-rc.1
overrides:
  vite@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
