name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '22'
          cache: true
          run-install: true

      - name: Build
        run: vp run build

      - name: Generate GitHub Changelog
        run: vpx changelogithub
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NPM
        run: vp pm publish -r --access public --no-git-checks
